/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OnlineMovie;

import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.table.DefaultTableModel;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;

/**
 *
 * @author asus
 */
public class GUIForm extends javax.swing.JFrame {
    
    /**
     * Creates new form GUIForm
     */
    private int mID;
    private String mName;
    private int duration;
    private String mGenre, mGenre1;
    private int rating;
    private int price;
    private String tAudience;
    private int discount;
    
    public GUIForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        MovieIDLabel = new javax.swing.JLabel();
        MovieNameLabel = new javax.swing.JLabel();
        PriceLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TargetedAudienceLabel = new javax.swing.JLabel();
        RatingLabel = new javax.swing.JLabel();
        MNameText = new javax.swing.JTextField();
        MGenreCombo = new javax.swing.JComboBox<>();
        MPriceText = new javax.swing.JTextField();
        MIDText = new javax.swing.JTextField();
        MDiscountText = new javax.swing.JTextField();
        ChildrenButton = new javax.swing.JRadioButton();
        FamilyButton = new javax.swing.JRadioButton();
        AdultsButton = new javax.swing.JRadioButton();
        TeenagersButton = new javax.swing.JRadioButton();
        AllButton = new javax.swing.JRadioButton();
        MRatingSlider = new javax.swing.JSlider();
        MRatingSlider.setPaintLabels(true);
        AddBtn = new javax.swing.JButton();
        MovieIDLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        MDurationText = new javax.swing.JTextField();
        ClearBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        SearchBtn = new javax.swing.JButton();
        JSearchPrice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        MGenreCombo1 = new javax.swing.JComboBox<>();
        jButtonDisplay = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        MTable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuImport = new javax.swing.JMenuItem();
        jMenuClose = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(7, 2147483647));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Online Movie Store");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(271, 271, 271))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        MovieIDLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MovieIDLabel.setText("Movie ID");

        MovieNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MovieNameLabel.setText("Movie Name");

        PriceLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PriceLabel.setText("Price");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Discount");

        TargetedAudienceLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TargetedAudienceLabel.setText("Targeted Audience");

        RatingLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RatingLabel.setText("Rating");

        MGenreCombo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MGenreCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Action", "Thriller", "Romantic", "Horror", "Sci-Fi", "Drama", "Comedy", " " }));
        MGenreCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MGenreComboActionPerformed(evt);
            }
        });

        MPriceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MPriceTextActionPerformed(evt);
            }
        });

        MDiscountText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MDiscountTextActionPerformed(evt);
            }
        });

        buttonGroup1.add(ChildrenButton);
        ChildrenButton.setText("Children");

        buttonGroup1.add(FamilyButton);
        FamilyButton.setText("Family");

        buttonGroup1.add(AdultsButton);
        AdultsButton.setText("Adults");

        buttonGroup1.add(TeenagersButton);
        TeenagersButton.setText("Teenagers");

        buttonGroup1.add(AllButton);
        AllButton.setText("All Age Groups");

        MRatingSlider.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MRatingSlider.setMaximum(5);
        MRatingSlider.setMinorTickSpacing(1);
        MRatingSlider.setPaintLabels(true);
        MRatingSlider.setPaintTicks(true);
        MRatingSlider.setToolTipText("");
        MRatingSlider.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        AddBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AddBtn.setText("Add to Store");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });

        MovieIDLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MovieIDLabel1.setText("Movie Genre");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Duration");

        ClearBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ClearBtn.setText("Clear");
        ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(MovieIDLabel)
                                .addGap(18, 18, 18)
                                .addComponent(MIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(MovieIDLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(MGenreCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(MovieNameLabel)
                                .addGap(18, 18, 18)
                                .addComponent(MNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(RatingLabel)
                                .addGap(28, 28, 28)
                                .addComponent(MRatingSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TargetedAudienceLabel)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChildrenButton)
                            .addComponent(TeenagersButton)
                            .addComponent(AllButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AdultsButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FamilyButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MDiscountText, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(MDurationText))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(PriceLabel)
                            .addGap(31, 31, 31)
                            .addComponent(MPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MovieIDLabel)
                            .addComponent(MIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MDurationText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(MovieNameLabel)
                                .addComponent(MNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MRatingSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(RatingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(MGenreCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(MovieIDLabel1))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(PriceLabel)
                                        .addComponent(MPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ChildrenButton)
                                    .addComponent(FamilyButton))
                                .addGap(3, 3, 3)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(TeenagersButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(AllButton))
                                    .addComponent(AdultsButton)))
                            .addComponent(TargetedAudienceLabel)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MDiscountText, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        MRatingSlider.getAccessibleContext().setAccessibleName("");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        SearchBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SearchBtn.setText("Search");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Search based on Price:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Available Movies:");

        MGenreCombo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MGenreCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Action", "Thriller", "Romantic", "Horror", "Sci-Fi", "Drama" }));

        jButtonDisplay.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonDisplay.setText("Display");
        jButtonDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDisplayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(MGenreCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButtonDisplay))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(JSearchPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchBtn)
                    .addComponent(JSearchPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MGenreCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDisplay))
                .addGap(24, 24, 24))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        MTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Genre", "Duration", "Audience", "Price", "Discount", "Rating"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        MTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(MTable);
        if (MTable.getColumnModel().getColumnCount() > 0) {
            MTable.getColumnModel().getColumn(0).setResizable(false);
            MTable.getColumnModel().getColumn(0).setPreferredWidth(2);
            MTable.getColumnModel().getColumn(1).setResizable(false);
            MTable.getColumnModel().getColumn(1).setPreferredWidth(180);
            MTable.getColumnModel().getColumn(2).setResizable(false);
            MTable.getColumnModel().getColumn(2).setPreferredWidth(80);
            MTable.getColumnModel().getColumn(3).setResizable(false);
            MTable.getColumnModel().getColumn(3).setPreferredWidth(20);
            MTable.getColumnModel().getColumn(4).setResizable(false);
            MTable.getColumnModel().getColumn(4).setPreferredWidth(80);
            MTable.getColumnModel().getColumn(5).setResizable(false);
            MTable.getColumnModel().getColumn(5).setPreferredWidth(10);
            MTable.getColumnModel().getColumn(6).setResizable(false);
            MTable.getColumnModel().getColumn(6).setPreferredWidth(25);
            MTable.getColumnModel().getColumn(7).setResizable(false);
            MTable.getColumnModel().getColumn(7).setPreferredWidth(10);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenuFile.setText("File");
        jMenuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFileActionPerformed(evt);
            }
        });

        jMenuImport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuImport.setText("Import");
        jMenuImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuImportActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuImport);

        jMenuClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuClose.setText("Close");
        jMenuClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCloseActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuClose);

        jMenuBar1.add(jMenuFile);

        jMenuHelp.setText("Help");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("About");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItem1);

        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//fullT = new FullTimeStaffHire(vacancyNumber,designation, jobType, salary, workingHour) ;             
//                staffHire.add(fullT);
    private void MPriceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MPriceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MPriceTextActionPerformed

    private void MDiscountTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MDiscountTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MDiscountTextActionPerformed

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        mID=(get_mID());
        mName=get_mName();
        duration=get_duration();
        mGenre=get_mGenre();
        rating=get_rating();
        price=get_price();
        tAudience=get_tAudience();
        discount=get_discount();
        if(mID<0){
            JOptionPane.showMessageDialog(jPanel2,"Invalid Input! Please enter a positive whole number for Movie ID!");
        }
        else if(mID_Check(mID)==false){
            JOptionPane.showMessageDialog(jPanel2,"Movie ID already exists! Please enter a different number for Movie ID!");
        }
        else if(mName.isEmpty()){
            JOptionPane.showMessageDialog(jPanel2,"Invalid Input! Please enter a Movie Name.");
        }
        else if(duration<0){
            JOptionPane.showMessageDialog(jPanel2,"Invalid Input! Please enter duration of the Movie!");
        }
        else if(price<0){
            JOptionPane.showMessageDialog(jPanel2,"Invalid Input! Please enter price of the Movie!");
        }
        else if(discount<0 || discount>price){
            if(discount>price){
                JOptionPane.showMessageDialog(jPanel2,"Invalid Input! Discount value exceeds price! Please enter a valid discount amount!");
            }
            else{
                JOptionPane.showMessageDialog(jPanel2,"Invalid Input! Please enter a valid discount amount!");
            }
        }
        else if(mGenre.equals(" ")){
            JOptionPane.showMessageDialog(jPanel2,"Invalid Input! Please select a genre for the Movie!");
        }
        else if(tAudience.equals("")){
            JOptionPane.showMessageDialog(jPanel2,"Invalid Input! Please select a targeted audience!");
        }
        else
        {
            DefaultTableModel model = (DefaultTableModel)MTable.getModel();
            model.addRow(new Object[]
            {
                String.valueOf(mID),mName,mGenre,String.valueOf(duration),tAudience,String.valueOf(price), String.valueOf(discount),String.valueOf(rating)
            }
            );
            JOptionPane.showMessageDialog(jPanel2,"Record Added!");
        }
    }//GEN-LAST:event_AddBtnActionPerformed

    private void jMenuCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuCloseActionPerformed

    private void jMenuImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuImportActionPerformed
        String filePath = "src/OnlineMovie/imp.csv";
        File file = new File(filePath);
        int success = 0;
        try {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
//          
            DefaultTableModel model = (DefaultTableModel)MTable.getModel();
            Object[] lines = br.lines().toArray();
            
            for(int i = 0; i < lines.length; i++){
               String[] row = lines[i].toString().split(",");
               if(mID_Check(Integer.parseInt(row[0]))==true){
                    model.addRow(row);
                    success = 1;
                }
            }
            if (success == 1){
                JOptionPane.showMessageDialog(jPanel2,"Rows have been added to table");
            }else{
                JOptionPane.showMessageDialog(jPanel2,"Values already exist in the table");
            }
                
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(jPanel2,"No file found in the location of drive.");
        }
    }//GEN-LAST:event_jMenuImportActionPerformed

    private void jMenuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuFileActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed

        if(get_searchPrice()<0){
            JOptionPane.showMessageDialog(jPanel2,"Invalid Input! Please enter valid price to search!");
        }
        else{
            String[][] movieList = get_tableData();

            SelectionSort.sort(movieList);
            int ans=BinarySearch.search(movieList, 0, (movieList.length)-1, get_searchPrice());

//          
            if(ans!=-1){
                JOptionPane.showMessageDialog(jPanel2,"Movie ID: " + movieList[ans][0] + "\nMovie Name: " + movieList[ans][1] + "\nMovie Genre: " + movieList[ans][2] + "\nMovie Duration: " + movieList[ans][3] + "\nTarget Audience: " + movieList[ans][4] + "\nRating: " + movieList[ans][7] + "\nDiscount: " + movieList[ans][6]);
            }
            else{
                JOptionPane.showMessageDialog(jPanel2,"There is no Movie available in the given price!");
            }
        }
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed
        MIDText.setText("");
        MNameText.setText("");
        MDurationText.setText("");
        MPriceText.setText("");
        MDiscountText.setText("");
        MRatingSlider.setValue(5);
        MGenreCombo.setSelectedIndex(0);
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_ClearBtnActionPerformed

    private void jButtonDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDisplayActionPerformed
        mGenre1 = get_mGenre1();
        ArrayList<String> match = new ArrayList();
        String[][] movieList = get_tableData();
        if(mGenre1.equals(" ")){
            JOptionPane.showMessageDialog(jPanel2,"Please select a genre to generate lsit of movies");
        }else{
            for (String[] movieItem : movieList) {
                if (movieItem[2].equals(mGenre1)) {
                    match.add(movieItem[1]);
                }    
            }
        }
        if (match.isEmpty()){
            JOptionPane.showMessageDialog(jPanel2,"N0 movies found from "+ mGenre1 +" Genre" );
        }else{
            String output = generate_list(match, mGenre1);
            JOptionPane.showMessageDialog(jPanel2, output);
        }   
    }//GEN-LAST:event_jButtonDisplayActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        File file=new File("src/OnlineMovie/userManual.pdf");
        try {
            Desktop.getDesktop().open(file);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "File not found");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MGenreComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MGenreComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MGenreComboActionPerformed

    /*size
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIForm().setVisible(true);
            }
        });
    }
    
    public int get_mID()
    {
        // try detects exceptions and catch handles them
        try{
            //Integer.parseInt converts any type of data into integer type
            int x=Integer.parseInt(MIDText.getText());
            return x;
        }
        catch(NumberFormatException a){
            int x=-1;
            return x;
        }
    }
     
    public String get_mName()
    {
        String x=MNameText.getText();
        return x;
    }
    
    public int get_duration()
    {
        // try detects exceptions and catch handles them
        try{
            //Integer.parseInt converts any type of data into integer type
            int x=Integer.parseInt(MDurationText.getText());
            return x;        
        }
        catch(NumberFormatException a){
            int x=-1;
            return x;
        }
    }
    
    public int get_price()
    {
        // try detects exceptions and catch handles them
        try{
            //Integer.parseInt converts any type of data into integer type
            int x=Integer.parseInt(MPriceText.getText());
            return x;
        }
        catch(NumberFormatException a){
            int x=-1;
            return x;
        }
    }
    
    public int get_discount()
    {
        // try detects exceptions and catch handles them
        try{
            //Integer.parseInt converts any type of data into integer type
            int x=Integer.parseInt(MDiscountText.getText());
            return x;
        }
        catch(NumberFormatException a){
            int x=-1;
            return x;
        }
    }
    
    public String get_mGenre()
    {
        String x=MGenreCombo.getSelectedItem().toString();
        return x;
    }
    public String get_mGenre1()
    {
        String x=MGenreCombo1.getSelectedItem().toString();
        return x;
    }
    
    public int get_rating()
    {
        int x=MRatingSlider.getValue();
        return x;
    }
    
    public String get_tAudience()
    {
        String x="";
        for (Enumeration<AbstractButton> mbuttons = buttonGroup1.getElements(); mbuttons.hasMoreElements();)
        {
            AbstractButton button = mbuttons.nextElement();
            if (button.isSelected())
            {
                x=button.getText();
                return x;
            }
        }
        return x;
    }
    
    public int get_searchPrice()
    {
        // try detects exceptions and catch handles them
        try{
            //Integer.parseInt converts any type of data into integer type
            int x=Integer.parseInt(JSearchPrice.getText());
            return x;
        }
        catch(NumberFormatException a){
            int x=-1;
            return x;
        }
    }
    
    // Checks whether same movie ID exists in the table or not
    public Boolean mID_Check(int id)
    {
        Boolean valid=true;
        int row=MTable.getRowCount();
        for(int i = 0; i < row; i++){
            if(id==Integer.parseInt((String)MTable.getValueAt(i,0))){
                valid=false;
            }
        }
        return valid;
    }
    
    public String[][] get_tableData()
    {
        String[][] movieList = new String[MTable.getRowCount()][8];  
            for (int i =0; i<MTable.getRowCount(); i++){
                for (int j =0; j<8; j++){
                    movieList[i][j]=(String) (MTable.getValueAt(i,j));
                } 
            }
               return movieList;
    }
    
    public String generate_list(ArrayList<String> match, String genre)
    {
        String output = "There are "+ match.size() + " movies in " + genre +" genre : \n" ;
        
        for(int i=0; i<match.size(); i++){
            output +=i +" .  " + match.get(i)+ "\n";
        };
        return output;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JRadioButton AdultsButton;
    private javax.swing.JRadioButton AllButton;
    private javax.swing.JRadioButton ChildrenButton;
    private javax.swing.JButton ClearBtn;
    private javax.swing.JRadioButton FamilyButton;
    private javax.swing.JTextField JSearchPrice;
    private javax.swing.JTextField MDiscountText;
    private javax.swing.JTextField MDurationText;
    private javax.swing.JComboBox<String> MGenreCombo;
    private javax.swing.JComboBox<String> MGenreCombo1;
    private javax.swing.JTextField MIDText;
    private javax.swing.JTextField MNameText;
    private javax.swing.JTextField MPriceText;
    private javax.swing.JSlider MRatingSlider;
    private javax.swing.JTable MTable;
    private javax.swing.JLabel MovieIDLabel;
    private javax.swing.JLabel MovieIDLabel1;
    private javax.swing.JLabel MovieNameLabel;
    private javax.swing.JLabel PriceLabel;
    private javax.swing.JLabel RatingLabel;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JLabel TargetedAudienceLabel;
    private javax.swing.JRadioButton TeenagersButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonDisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuClose;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuImport;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private Object String(int mID) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
